# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 13:16
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Article',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=100)),
				('slug', models.SlugField(max_length=20, unique=True)),
				('perex', models.TextField()),
				('content', models.TextField()),
				('published', models.CharField(choices=[('y', 'Published'), ('n', 'Not published')], max_length=1)),
				('big_integer_field', models.BigIntegerField()),
				('binary_field', models.BinaryField()),
				('boolean_fied', models.BooleanField()),
				('char_field', models.CharField(max_length=100)),
				('date_field', models.DateField()),
				('date_time_field', models.DateTimeField()),
				('decimal_field', models.DecimalField(decimal_places=0, max_digits=10)),
				('duration_field', models.DurationField()),
				('email_field', models.EmailField(max_length=254)),
				('file_field', models.FileField(upload_to='')),
				('float_field', models.FloatField()),
				('integer_field', models.IntegerField()),
				('image_field', models.ImageField(upload_to='')),
				('ip_address_field', models.GenericIPAddressField()),
				('null_boolean_field', models.BooleanField(null=True)),
				('positive_integer_field', models.PositiveIntegerField()),
				('positive_small_integer_field', models.PositiveSmallIntegerField()),
				('slug_field', models.SlugField()),
				('small_integer_field', models.SmallIntegerField()),
				('text_field', models.TextField()),
				('time_field', models.TimeField()),
				('url_field', models.URLField()),
				('uuid_field', models.UUIDField()),
			],
		),
		migrations.CreateModel(
			name='Category',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100)),
				('slug', models.SlugField(max_length=20, unique=True)),
			],
		),
		migrations.AddField(
			model_name='article',
			name='category',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Category'),
		),
	]
